---
title: "Midterm Project: DATA474 Qian"
author: "Weslee Nguyen and Sedona O'Hearn"
format: pdf
editor: visual
---

# Libraries

```{r}
#| echo: false
#| warning: false

library(tidyverse)
library(dplyr)
library(ggplot2)
library(mice)     # For imputation
library(igraph)   # To later visualize highly correlated vars
```

# CHF Classification

## Step #1: Preprocessing

```{r}

albumin_creatinine <- read.csv("Datasets/albumin-creatinine.csv")
biochem_panel <- read.csv("Datasets/biochem_panel.csv")
blood_pressure <- read.csv("Datasets/blood_pressure.csv")
body_measures <- read.csv("Datasets/body_measures.csv")
CBC <- read.csv("Datasets/CBC.csv")
cigarettes <- read.csv("Datasets/cigarettes.csv")
demographics <- read.csv("Datasets/demographics.csv")
diabetes <- read.csv("Datasets/diabetes.csv")
diet_second_day <- read.csv("Datasets/diet_second_day.csv")
environmental_pollutants <- read.csv("Datasets/environmental_pollutants.csv")
medical_conditions <- read.csv("Datasets/medical_conditions.csv")
mental_health <- read.csv("Datasets/mental_health.csv")
physical_activity <- read.csv("Datasets/physical_activity.csv")

datasets <- list(
  albumin_creatinine,
  biochem_panel,
  blood_pressure,
  body_measures,
  CBC,
  cigarettes,
  demographics,
  diabetes,
  diet_second_day,
  environmental_pollutants,
  medical_conditions,
  mental_health,
  physical_activity
)

# There's column X in all of them, get rid of it
datasets_clean <- map(datasets, ~ select(.x, -any_of("X")))

# Merge all datasets by unique participant identifier SEQN
NHANES <- reduce(datasets_clean, inner_join, by = "SEQN")

# Only retain adults and people who answered Y/N to CHF
NHANES <- NHANES %>% filter(RIDAGEYR >= 18, MCQ160B %in% c(1, 2)) %>%
  mutate(CHF = if_else(MCQ160B == 1, 1, 0)) %>%
  select(-MCQ160B)

# Factorize for classification; 1 = Has CHF, 0 = No CHF
NHANES$CHF <- factor(NHANES$CHF, levels = c(0, 1))

# Drop empty predictors (>30% NAs)
NA_vars <- NHANES %>%
  summarise(across(everything(), ~ mean(is.na(.), na.rm = FALSE))) %>%
  pivot_longer(
    cols = everything(), 
    names_to = "variable", 
    values_to = "NA_percent") %>%
  arrange(desc(NA_percent))

# Many variables tossed as they're kid-specific e.g. head circumference
# BMI Variables to Toss: BMXRECUM, BMIRECUM, BMXHEAD, BMDBMIC, BMIHT, BMIARM, 
      # BMIARMC, BMIWAIST, BMIWT, BMIHIP, BMILEG
# Smoking Variables: SMQ040, SMQ621, SMD630, SMD641, SMD650, SMD100MN
# Demographics: RIDAGEMN, RIDEXAGM, RIDEXPRG, DMDYRUSR, DMDHRGND, DMDHRAGZ
      # DMDHREDZ, DMDHRMAZ, DMDHSEDZ
# Medical Conditions: MCQ149 (Liver),  MCQ500 (Cancer), MCQ230A-D (Cancer)
      # MCQ510A-F (Cancer, all), MCQ035 + MCQ040 (Asthma), MCQ050 (Thyroid)
      # MCQ170L/M (Liver + Thyroid), MCQ195 (Arthritis)
# Diabetes: DIQ040 (Age of Dx), DIQ050 (insulin), DIQ060 + DIQ060U (Meds), DIQ070
# Mental Health: DPQ100 (Depression score)
# Physical Activity: PAD820 (Leisurely Activity)
# Diet Recall: DR2SKY (Sugar intake), DR2DBIH (Dietary intake)
# Lab work: LBXSLDSI (Serum Sodium)

vars_to_keep <- NA_vars %>%
  filter(NA_percent <= 0.3) %>%
  pull(variable)

NHANES <- NHANES %>% select(any_of(vars_to_keep))

##### MULTICOLLINEARITY: Remove vars basically the same, else MICE crashes
numeric_vars <- NHANES %>% select(where(is.numeric))
cor_matrix <- cor(numeric_vars, use = "pairwise.complete.obs") # Avoid NAs

cor_pairs <- cor_matrix %>%
  as.data.frame() %>%
  rownames_to_column(var = "var1") %>%
  pivot_longer(-var1, names_to = "var2", values_to = "cor") %>%
  filter(var1 != var2) %>%          # remove diagonal as cor = 1
  filter(abs(cor) > 0.95) %>%       # threshold cor = 0.95
  arrange(desc(abs(cor)))

cor_pairs

# Turn cor_pairs into graph to see connected components
# Remove from each component till there's only one member
edges <- cor_pairs %>% select(var1, var2)
g <- graph_from_data_frame(edges, directed = FALSE)
clusters <- components(g)
clusters$membership

# There's 30 clusters = remove at least 30 variables
# Simply chose 1 per cluster
# Any lab variables = starts with LBX; diet = DR2, body measure = LBD, urine = URX
NHANES <- NHANES %>% select(-c(LBXSTB, LBDSGBSI, LBDSTPSI, LBDSALSI, URXUMS, 
                 URXCRS, WTPH2YR.y, WTPH2YR.x, LBDBMNSI, LBDBCDSI, LBDSCRSI, 
                 LBDTHGSI, LBDSUASI, LBDSCHSI, LBDSTRSI, LBDBPBSI, LBDBSESI, 
                 LBDSBUSI, LBDSPHSI, LBDSIRSI, DR2TM181, DR2TP182, DR2DRSTZ, 
                 LBDSGLSI, DR2TP226, DR2TS160, DR2TFDFE, LBXHCT, DR2TP225, 
                 DR2TS060, DR2TS140, LBDSCASI, RIDRETH3, BPXOPLS1, WTMEC2YR, 
                 DR2TTFAT, DR2TS180))

##### IMPUTATION: Use MICE to imputate remaining missing data
# Handles continuous and categorical data
# Treat NA variable as dependent, regress on all other variables
# Predictive Mean Matching (PMM): Find other cases w/ similar predicted values, 
      # then randomly choose one of their actual observed values for imputation--
      # thus assumes data is missing at random (no pattern)
# m = 5 imputed datasets made for stabilized guessing

imputation <- mice(NHANES, m = 1, method = "pmm", seed = 123)
NHANES <- complete(imputation)

# Export to make sure it's never ruined!
NHANES_cleaned <- write.csv(NHANES, "NHANES_cleaned.csv")
```

Documentation:

-   [Albumin-Creatinine](https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/ALB_CR_L.htm)

-   [Biochemistry Panel](https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/BIOPRO_L.htm)

-   [Blood Pressure](https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/BPXO_L.htm)

-   [Body Measures](https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/BMX_L.htm)

-   [Complete Blood Count](https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/CBC_L.htm)

-   [Cigarettes](https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/SMQ_L.htm)

-   [Demographics](https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/DEMO_L.htm#SEQN)

-   [Diabetes](https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/DIQ_L.htm)

-   [Diet](https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/DR2TOT_L.htm#DR2TP182)

-   [Environmental Pollutants](https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/PBCD_L.htm)

-   [Medical Conditions](https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/MCQ_L.htm#MCQ160b)

-   [Mental Health](https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/DPQ_L.htm#DPQ070)

-   [Physical Activity](https://wwwn.cdc.gov/Nchs/Data/Nhanes/Public/2021/DataFiles/PAQ_L.htm)
